### ISSUE TITLE
Multi-player

### ISSUE THREAD

**Issue by HugoBuscemi** [tinylinux/m1platformer#18]
Ajouter le mode multi-joueur

**Comment by HugoBuscemi** [comment]
- [ ] Récupération du nombre de joueurs
- [ ] Touche de saut pour chaque joueur
- [ ] Création des joueurs
- [ ] Update de tous les joueurs
- [ ] Gestion de la mort (!= pour juste 1 joueur => score)

**Comment by tinylinux** [comment]
Ajout du menu pour configurer le multi-joueur

**Comment by tinylinux** [comment]
Multijoueur terminé.
