### ISSUE TITLE
Menu principal

### ISSUE THREAD

**Issue by SamuelArsac** [tinylinux/m1platformer#6]
Création du menu principal

**Comment by tinylinux** [comment]
Génération d'une variable `state` (en format int) : 
1. menu principal
2. in game
3. pause ?

**Comment by tinylinux** [comment]
**En l'état actuel des choses :**

Un menu de départ a été fait. 
(Pseudo, Jouer, Quitter)


Ce qu'il reste à faire :
- Affichage du scoreboard
